### PR TITLE
Add Ollama model unload functionality to Plush-for-ComfyUI

### PR DESCRIPTION
**Pull request by 9nate-drake**
- Add ollama_unload_request class to api_requests.py for proper REST-based model unloading
- Integrate model unload functionality into AdvPromptEnhancer node
- Use proper error handling and logging consistent with codebase
- Maintain compatibility with existing request context pattern

This change allows users to automatically unload Ollama models after completion, improving memory management when integrating with high memory requirement models (Flux, video models)

### CODE REVIEW

**Comment by 9nate-drake** [comment]
This could work/be modified for other local LLM's too, but untested at the moment

**Comment by glibsonoran** [comment]
Hey @9nate-drake thanks for the code, that certainly made this easier.  Your approach was right on.  I did change a few things but having your code made it much more straight forward.  I'm going to provide the user with three options as you can see in the attached image. 
The cmd window output in the image is showing the state of the loaded models using: 'ollama ps' after different runs using different settings.  Seems to work well.  I'll probably load it up to live tomorrow:

Ollama_Unload

**Comment by 9nate-drake** [comment]
Thanks. Great node

**Comment by glibsonoran** [comment]
@9nate-drake The new version 1.21.21 is up, please give it a workout to make sure there are no bugs.  I gave you a little attribution in the ReadMe file... thanks :)

**Comment by glibsonoran** [comment]
closed

**Pull request closed without merging**
